DROP TABLE doctors;
--;;
DROP TABLE doctors_to_organizations;
--;;
DROP TABLE doctors_to_specializations;
--;;
DROP TABLE documents;
--;;
DROP TABLE event_types;
--;;
DROP TABLE events;
--;;
DROP TABLE schema_migrations;
--;;
DROP TABLE specializations;
--;;
DROP TABLE users;
--;;
